---
name: tf-fmt
description: Format files using tf
author: Kamil Zabielski

inputs:
  chroot-directory:
    description: Directory to chroot into before running terraform fmt
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: Run tf-fmt
      working-directory: ${{ inputs.chroot-directory }}
      shell: bash
      run: |
        opentofu fmt -check -recursive .