---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/.github/workflows"
      - "/src/tofu-*"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directories:
      - "/tst/*"
    schedule:
      interval: "weekly"
