---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/.github/workflows"
      - "/actions/*"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directories:
      - "/test-fixtures/*"
    schedule:
      interval: "weekly"
