---
name: tf-fmt
description: Format files using tofu
author: Kamil Zabielski

branding:
  icon: git-merge
  color: gray-dark

inputs:
  chroot-directory:
    description: Directory to chroot into before running tofu fmt
    required: false
    default: "."

outputs:
  status-code:
    description: Exit code from tofu fmt
    value: ${{ steps.tf-fmt.outputs.status-code }}

runs:
  using: "composite"
  steps:
    - name: Run tofu fmt
      id: tf-fmt
      working-directory: ${{ inputs.chroot-directory }}
      shell: bash
      run: |
        status_code=0
        echo "::group::Run tofu fmt"
        tofu fmt -check -recursive . || status_code=$?
        echo "::endgroup::"
        echo "status-code=$status_code" >> "$GITHUB_OUTPUT"
        exit "$status_code"
