---
name: tofu-github-comment
description: Add a GitHub comment with the OpenTofu plan summary
author: Kamil Zabielski

branding:
  icon: git-merge
  color: gray-dark

outputs:
  comment-id:
    description: ID of the created or updated pull request comment.
    value: ${{ steps.add-plan-summary-comment.outputs.comment-id }}

inputs:
  comment-file-path:
    description: The path to the pre-generated plan comment file. One of comment-file-path or comment-artifact-name must be provided.
    required: false
    default: ""
  comment-artifact-name:
    description: The name of the GitHub Actions artifact containing the pre-generated plan comment file. Takes precedence over comment-file-path if both are provided. One of comment-file-path or comment-artifact-name must be provided.
    required: false
    default: ""
  comment-identifier:
    description: Optional identifier to let the action update the same comment instead of posting new ones.
    required: false
    default: ""
  github-token:
    description: GitHub token used to create the pull request comment. Defaults to github.token.
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Either comment-file-path or comment-artifact-name must be provided
      if: ${{ inputs.comment-file-path == '' && inputs.comment-artifact-name == '' }}
      shell: bash
      run: |
        echo "::error::Either comment-file-path or comment-artifact-name must be provided"
        exit 1

    - name: Only one of comment-file-path or comment-artifact-name must be provided
      if: ${{ inputs.comment-file-path != '' && inputs.comment-artifact-name != '' }}
      shell: bash
      run: |
        echo "::error::Only one of comment-file-path or comment-artifact-name must be provided"
        exit 1

    - name: Download comment artifact if comment-artifact-name is provided
      if: ${{ inputs.comment-artifact-name != '' }}
      id: download-comment-artifact
      uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7
      with:
        name: ${{ inputs.comment-artifact-name }}
        path: ${{ runner.temp }}

    - name: Set comment-file-path
      id: set-comment-file-path
      shell: bash
      run: |
        if [[ "${{ inputs.comment-artifact-name }}" != "" ]]; then
          echo "comment-file-path=${{ steps.download-comment-artifact.outputs.download-path }}/${{ inputs.comment-artifact-name }}" >> "$GITHUB_OUTPUT"
        else
          echo "comment-file-path=${{ inputs.comment-file-path }}" >> "$GITHUB_OUTPUT"
        fi

    - name: Add plan summary comment
      if: ${{ github.event_name == 'pull_request' }}
      id: add-plan-summary-comment
      uses: thollander/actions-comment-pull-request@e4a76dd2b0a3c2027c3fd84147a67c22ee4c90fa
      with:
        github-token: ${{ inputs.github-token || github.token }}
        file-path: ${{ steps.set-comment-file-path.outputs.comment-file-path }}
        comment-tag: ${{ inputs.comment-identifier }}
