---
name: tofu-taint
description: Taint a resource using tofu
author: Kamil Zabielski

branding:
  icon: git-merge
  color: gray-dark

inputs:
  chroot-directory:
    description: Directory to chroot into before running tofu taint
    required: false
    default: "."
  address:
    description: The address of the resource to taint
    required: true
  allow-missing:
    description: |
      If specified, the command will succeed even if the resource is missing.
      Defaults to false.
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Run tofu taint
      uses: actions/github-script@f28e40c0e1e4751b89fc1b0bb2e99ba255654b38 # v7.1.0
      with:
        script: |
          const core = require('@actions/core');
          const {exec} = require('@actions/exec');

          core.startGroup('Run tofu taint');
          try {
            await exec('tofu', [
              'taint',
              '-allow-missing=${{ inputs.allow-missing }}',
              '${{ inputs.address }}',
            ], { cwd: '${{ inputs.chroot-directory }}' });
          } finally {
            core.endGroup();
          }
