---
name: Continuous integration
run-name: Continuous integration

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ '**' ]

permissions:
  contents: read

env:
  TEST_FIXTURES_DIR: test-fixtures

jobs:
  actionlint:
    name: lint / actionlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Run actionlint
        uses: raven-actions/actionlint@205b530c5d9fa8f44ae9ed59f341a0db994aa6f8
        with:
          actionlint_flags: .github/workflows/*.yaml

  get-tofu-releases:
    name: setup / prepare tofu releases
    runs-on: ubuntu-slim
    outputs:
      releases: ${{ steps.read-releases.outputs.releases }}
      releases-with-lockfile: ${{ steps.read-releases.outputs.releases-with-lockfile }}
    steps:
      - name: Restore cached releases
        id: cache-releases
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: .cache/tofu-releases.json
          key: tofu-releases-v1
          restore-keys: |
            tofu-releases-

      - name: Fetch releases if cache missed
        id: get-tofu-releases
        if: steps.cache-releases.outputs.cache-hit != 'true'
        shell: bash
        run: |
          mkdir -p .cache
          releases="$(curl -s 'https://api.github.com/repos/opentofu/opentofu/releases' | jq -c '
            map(select(.prerelease == false)) |
            map(.tag_name | sub("^v";"")) |
            map(select(test("^[0-9]+\\.[0-9]+\\.[0-9]+$"))) |
            map(split(".") | {major:(.[0]|tonumber), minor:(.[1]|tonumber), patch:(.[2]|tonumber), ver:(.[0]+"."+.[1]+"."+.[2])}) |
            sort_by(.major,.minor,.patch) |
            group_by(.major,.minor) |
            map(last.ver)
          ')"
          echo "$releases" > .cache/tofu-releases.json

      - name: Read releases
        id: read-releases
        shell: bash
        run: |
          releases="$(cat .cache/tofu-releases.json)"
          echo "$releases"
          echo "releases=$releases" >> "$GITHUB_OUTPUT"
          releases_with_lockfile="$(echo "$releases" | jq -c 'map(select(split(".") | (.[0]|tonumber) * 100 + (.[1]|tonumber) >= 110))')"
          echo "releases-with-lockfile=$releases_with_lockfile" >> "$GITHUB_OUTPUT"

  unit-setup:
    name: unit - tofu-setup
    needs: 
      - get-tofu-releases
    uses: ./.github/workflows/unit-setup.yaml
    with:
      tofu-versions: ${{ needs.get-tofu-releases.outputs.releases }}

  unit-setup-version-file:
    name: unit - tofu-setup with tofu-version-file
    needs:
      - get-tofu-releases
    uses: ./.github/workflows/unit-setup-version-file.yaml
    with:
      tofu-version: ${{ fromJson(needs.get-tofu-releases.outputs.releases)[0] }}

  unit-unlock-state:
    name: unit - tofu-unlock
    needs:
      - get-tofu-releases
    uses: ./.github/workflows/unit-unlock-state.yaml
    with:
      tofu-versions: ${{ needs.get-tofu-releases.outputs.releases-with-lockfile }}

  unit-fmt:
    name: unit - tofu-fmt
    needs: 
      - get-tofu-releases
    uses: ./.github/workflows/unit-fmt.yaml
    with:
      tofu-versions: ${{ needs.get-tofu-releases.outputs.releases }}

  unit-plan:
    name: unit - tofu-plan
    needs: 
      - get-tofu-releases
    uses: ./.github/workflows/unit-plan.yaml
    with:
      tofu-versions: ${{ needs.get-tofu-releases.outputs.releases }}

  unit-taint:
    name: unit - tofu-taint
    needs:
      - get-tofu-releases
    uses: ./.github/workflows/unit-taint.yaml
    with:
      tofu-versions: ${{ needs.get-tofu-releases.outputs.releases }}

  unit-import:
    name: unit - tofu-import
    needs:
      - get-tofu-releases
    uses: ./.github/workflows/unit-import.yaml
    with:
      tofu-versions: ${{ needs.get-tofu-releases.outputs.releases }}

  unit-env:
    name: unit - tofu-env
    uses: ./.github/workflows/unit-env.yaml

  integration-plan:
    name: integration / plan
    runs-on: ubuntu-slim
    outputs:
      plan-has-changes: ${{ steps.tf-plan.outputs.plan-has-changes }}
      plan-artifact-name: ${{ steps.tf-plan.outputs.plan-artifact-name }}
      tofu-version: ${{ matrix.tofu-version }}
    strategy:
      fail-fast: true
      matrix:
        tofu-version:
          - 1.11.5
        chroot-directory:
          - plan-with-changes
    steps:
      - name: Checkout the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Run tofu setup
        uses: ./actions/tofu-setup
        with:
          tofu-version: ${{ matrix.tofu-version }}

      - name: Run tofu plan
        id: tf-plan
        uses: ./actions/tofu-plan
        with:
          chroot-directory: ${{ env.TEST_FIXTURES_DIR }}/${{ matrix.chroot-directory }}
          environment: integration
          upload-artifact: 'true'

      - name: Assert resources to be added
        shell: bash
        run: |
          [[ "${{ steps.tf-plan.outputs.plan-has-changes }}" = "true" ]]
          [[ "${{ steps.tf-plan.outputs.plan-add-count }}" = "1" ]]

  integration-apply-with-artifact:
    name: integration / apply with artifact
    runs-on: ubuntu-slim
    needs: 
      - integration-plan
    steps:
      - name: Checkout the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Run tofu setup
        uses: ./actions/tofu-setup
        with:
          tofu-version: ${{ needs.integration-plan.outputs.tofu-version }}

      - name: Run tofu apply with artifact
        id: tf-apply-with-artifact
        uses: ./actions/tofu-apply
        with:
          chroot-directory: ${{ env.TEST_FIXTURES_DIR }}/plan-with-changes
          environment: integration
          plan-artifact-name: ${{ needs.integration-plan.outputs.plan-artifact-name }}

      - name: Run tofu plan for destroy
        id: tf-plan-destroy
        uses: ./actions/tofu-plan
        with:
          chroot-directory: ${{ env.TEST_FIXTURES_DIR }}/plan-with-changes
          environment: integration
          tofu-destroy: 'true'
          upload-artifact: 'false'

      - name: Assert resources to be removed
        shell: bash
        run: |
          [[ "${{ steps.tf-plan-destroy.outputs.plan-has-changes }}" = "true" ]]
          [[ "${{ steps.tf-plan-destroy.outputs.plan-destroy-count }}" = "1" ]]

      - name: Run tofu apply for destroy
        id: tf-apply-destroy
        uses: ./actions/tofu-apply
        with:
          chroot-directory: ${{ env.TEST_FIXTURES_DIR }}/plan-with-changes
          environment: integration
          plan-file-path: ${{ steps.tf-plan-destroy.outputs.plan-file-path }}

  integration-skeleton:
    name: integration / skeleton (${{ matrix.chroot-directory }})
    needs:
      - integration-plan
    strategy:
      fail-fast: true
      matrix:
        include:
          - chroot-directory: plan-with-changes
          - chroot-directory: plan-without-changes
    uses: ./.github/workflows/skeleton-plan-apply.yaml
    secrets: inherit
    with:
      tofu-version: ${{ needs.integration-plan.outputs.tofu-version }}
      chroot-directory: test-fixtures/${{ matrix.chroot-directory }}
      environment: integration

  integration-skeleton-apply-disabled:
    name: integration / skeleton apply disabled (${{ matrix.chroot-directory }})
    needs:
      - integration-plan
    strategy:
      fail-fast: true
      matrix:
        include:
          - chroot-directory: plan-with-changes
          - chroot-directory: plan-without-changes
    uses: ./.github/workflows/skeleton-plan-apply.yaml
    secrets: inherit
    with:
      tofu-version: ${{ needs.integration-plan.outputs.tofu-version }}
      chroot-directory: test-fixtures/${{ matrix.chroot-directory }}
      environment: integration
      tofu-apply: false

  integration-skeleton-version-file:
    name: integration / skeleton version file
    needs:
      - integration-plan
    strategy:
      fail-fast: true
      matrix:
        include:
          - chroot-directory: plan-with-changes
          - chroot-directory: plan-without-changes
    uses: ./.github/workflows/skeleton-plan-apply.yaml
    secrets: inherit
    with:
      tofu-version-file: test-fixtures/tofu-version/.tofu-version
      chroot-directory: test-fixtures/${{ matrix.chroot-directory }}
      environment: integration

  integration-skeleton-static-analysis:
    name: integration / skeleton static-analysis (${{ matrix.chroot-directory }})
    needs:
      - integration-plan
    strategy:
      fail-fast: true
      matrix:
        include:
          - chroot-directory: plan-with-changes
          - chroot-directory: plan-without-changes
    uses: ./.github/workflows/skeleton-static-analysis.yaml
    secrets: inherit
    with:
      tofu-version: ${{ needs.integration-plan.outputs.tofu-version }}
      chroot-directory: test-fixtures/${{ matrix.chroot-directory }}

  integration-skeleton-static-analysis-version-file:
    name: integration / skeleton static-analysis version file
    needs:
      - integration-plan
    strategy:
      fail-fast: true
      matrix:
        include:
          - chroot-directory: plan-with-changes
          - chroot-directory: plan-without-changes
    uses: ./.github/workflows/skeleton-static-analysis.yaml
    secrets: inherit
    with:
      tofu-version-file: test-fixtures/tofu-version/.tofu-version
      chroot-directory: test-fixtures/${{ matrix.chroot-directory }}
