---
name: Continuous Integration
run-name: ci-${{ github.event_name == 'pull_request' && github.event.number || github.run_number }}


on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ '**' ]

jobs:

  get-tofu-releases:
    runs-on: ubuntu-slim
    outputs:
      releases: ${{ steps.get-releases.outputs.releases }}
    steps:
      - name: Get last 10 tofu releases
        id: get-releases
        shell: bash
        run: |
          releases="$(curl -s 'https://api.github.com/repos/opentofu/opentofu/releases?per_page=10' | jq -c '[.[].tag_name | sub("^v";"")]')"
          echo "releases=$releases" >> "$GITHUB_OUTPUT"

  unit-setup:
    needs: 
      - get-tofu-releases
    strategy:
      fail-fast: true
      matrix:
        tofu-version: ${{ fromJson(needs.get-tofu-releases.outputs.releases) }}
    runs-on: ubuntu-slim
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6

      - name: Run tofu setup
        uses: ./src/tofu-setup
        id: tofu-setup
        with:
          tofu-version: ${{ matrix.tofu-version }}

      - name: Assert tofu setup by checking version
        shell: bash
        run: |
          echo "::group::Show tofu version"
          tofu version
          echo "::endgroup::"

          echo "::group::Check tofu version"
          [ "$(tofu version -json | yq -r '.terraform_version')" = "${{ matrix.tofu-version }}" ] && exit 0 || exit 1
          echo "::endgroup::"

  unit-fmt:
    runs-on: ubuntu-slim
    needs:
      - get-tofu-releases
    strategy:
      matrix:
        tofu-version: ${{ fromJson(needs.get-tofu-releases.outputs.releases) }}
        chroot-directory:
          - tst/fmt-ok
          - tst/fmt-failed
        include:
          - chroot-directory: tst/fmt-ok
            status-code: '0'
          - chroot-directory: tst/fmt-failed
            status-code: '3'
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6

      - name: Run tofu setup
        uses: ./src/tofu-setup
        with:
          tofu-version: ${{ matrix.tofu-version }}

      - name: Run tofu fmt
        id: tf-fmt
        uses: ./src/tofu-fmt
        continue-on-error: true
        with:
          chroot-directory: ${{ matrix.chroot-directory }}

      - name: Assert tofu fmt status code
        run: |
          echo "::group::Check tofu fmt status code"
          [ ${{ steps.tf-fmt.outcomes.status-code }} = ${{ matrix.status-code }} ] && exit 0 || exit 1
          echo "::endgroup::"

  tf-plan-apply-no-changes:
    runs-on: ubuntu-slim
    strategy:
      fail-fast: false
      matrix:
        chroot-directory:
          - tst/plan-without-changes
        tofu-version:
          - 1.6.0
          - 1.7.0
        tofu-apply:
          - 'true'
          - 'false'
        tofu-destroy:
          - 'false'
          - 'true'
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6

      - name: Run tofu setup
        uses: ./src/tofu-setup
        with:
          tofu-version: ${{ matrix.tofu-version }}

      - name: Run tofu plan for apply test fixture
        id: tf-plan
        uses: ./src/tofu-plan
        with:
          chroot-directory: ${{ matrix.chroot-directory }}
          environment: ${{ matrix.tofu-version }}
          upload-artifact: ${{ matrix.upload-artifact }}

      - name: Run tofu apply with file path
        id: tf-apply-no-artifact
        uses: ./src/tofu-apply
        if: matrix.tofu-apply == 'true' && matrix.upload-artifact == 'false' && steps.tf-plan.outputs.plan-has-changes == 'true'
        with:
          environment: ${{ matrix.tofu-version }}
          chroot-directory: ${{ matrix.chroot-directory }}
          plan-file-path: ${{ steps.tf-plan.outputs.plan-file-path }}

      - name: Run tofu apply with artifact
        id: tf-apply-with-artifact
        uses: ./src/tofu-apply
        if: matrix.tofu-apply == 'true' && matrix.upload-artifact == 'true' && steps.tf-plan.outputs.plan-has-changes == 'true'
        with:
          chroot-directory: ${{ matrix.chroot-directory }}
          environment: ${{ matrix.tofu-version }}
          plan-artifact-name: ${{ steps.tf-plan.outputs.plan-artifact-name }}

      - name: Run tofu plan for destroy test fixture
        id: tf-plan-destroy
        uses: ./src/tofu-plan
        if: matrix.tofu-destroy == 'true'
        with:
          chroot-directory: ${{ matrix.chroot-directory }}
          environment: ${{ matrix.tofu-version }}
          tofu-destroy: '${{ matrix.tofu-destroy }}'
          upload-artifact: '${{ matrix.upload-artifact }}'

      - name: Run tofu apply for destroy test fixture
        id: tf-apply-destroy
        uses: ./src/tofu-apply
        if: matrix.tofu-destroy == 'true' && steps.tf-plan-destroy.outputs.plan-has-changes == 'true'
        with:
          chroot-directory: ${{ matrix.chroot-directory }}
          environment: ${{ matrix.tofu-version }}
          plan-file-path: ${{ steps.tf-plan-destroy.outputs.plan-file-path }}