---
name: Skeleton - root checks

on:
  workflow_call:
    inputs:
      chroot-directory:
        description: Root directory to check.
        required: true
        type: string
      require-tofu-version-file:
        description: Require a .tofu-version file in the root directory.
        required: false
        type: boolean
        default: true
      require-lock-file:
        description: Require a .terraform.lock.hcl file in the root directory.
        required: false
        type: boolean
        default: true

permissions:
  contents: read

jobs:
  root-check:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout the repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6

      - name: Checkout tact
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6
        with:
          repository: kordega/tact
          ref: ${{ github.repository == 'kordega/tact' && github.ref || 'main' }}
          path: .tact

      - name: Check tofu root
        uses: ./.tact/actions/tofu-root-check
        with:
          chroot-directory: ${{ inputs.chroot-directory }}
          require-tofu-version-file: ${{ inputs.require-tofu-version-file }}
          require-lock-file: ${{ inputs.require-lock-file }}
