---
name: Skeleton - tact tests

on:
  workflow_call:
    inputs:
      tofu-version:
        description: |
          Version of opentofu to install.
        required: false
        type: string
      tofu-version-file:
        description: |
          Path to a file containing the opentofu version to install.
        required: false
        type: string
      run-tofu-fmt:
        description: |
          Run tofu fmt check.
          Defaults to true.
        required: false
        type: boolean
        default: true
      run-tofu-policy-check:
        description: |
          Run the rego policy checks against the tofu configuration.
          Defaults to true.
        required: false
        type: boolean
        default: true

permissions:
  contents: read

jobs:
  tofu-fmt:
    if: inputs.run-tofu-fmt
    runs-on: ubuntu-slim
    steps:
      - name: Checkout the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Checkout tact
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: kordega/tact
          ref: ${{ github.repository == 'kordega/tact' && github.ref || 'main' }}
          path: .tact

      - name: Run tofu setup
        uses: ./.tact/actions/tofu-setup
        with:
          tofu-version: ${{ inputs.tofu-version }}
          tofu-version-file: ${{ inputs.tofu-version-file }}

      - name: Run tofu fmt
        uses: ./.tact/actions/tofu-fmt

  tofu-policy-check:
    if: inputs.run-tofu-policy-check
    runs-on: ubuntu-slim
    steps:
      - name: Checkout the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Checkout tact
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: kordega/tact
          ref: ${{ github.repository == 'kordega/tact' && github.ref || 'main' }}
          path: .tact

      - name: Run tofu policy check
        uses: ./.tact/actions/tofu-policy-check
