---
name: Skeleton - tact tests

on:
  workflow_call:
    inputs:
      tofu-version:
        description: Version of opentofu to install.
        required: false
        type: string
      tofu-version-file:
        description: Path to a file containing the opentofu version to install.
        required: false
        type: string
      chroot-directory:
        description: Directory to chroot into before running tofu commands.
        required: false
        default: "."
        type: string

permissions:
  contents: read

jobs:
  tofu-fmt:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout the repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6

      - name: Checkout tact
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6
        with:
          repository: kordega/tact
          ref: ${{ github.repository == 'kordega/tact' && github.ref || 'main' }}
          path: .tact

      - name: Run tofu setup
        uses: ./.tact/actions/tofu-setup
        with:
          tofu-version: ${{ inputs.tofu-version }}
          tofu-version-file: ${{ inputs.tofu-version-file }}

      - name: Run tofu fmt
        uses: ./.tact/actions/tofu-fmt
        with:
          chroot-directory: ${{ inputs.chroot-directory }}
