name: Unit - tofu-setup with tofu-version-file

on:
  workflow_call:
    inputs:
      tofu-version:
        description: OpenTofu version to write into the version file.
        required: true
        type: string

permissions:
  contents: read

jobs:
  tofu-setup-version-file:
    name: unit / tofu-setup with tofu-version-file
    runs-on: ubuntu-slim
    steps:
      - name: Checkout the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Prepare tofu version file
        shell: bash
        run: |
          mkdir -p .cache
          echo "${{ inputs.tofu-version }}" > .cache/tofu-version.txt

      - name: Run tofu setup with tofu version file
        id: tofu-setup
        uses: ./actions/tofu-setup
        with:
          tofu-version-file: .cache/tofu-version.txt

      - name: Assert tofu setup by checking version
        shell: bash
        run: |
          echo "::group::Show tofu version"
          tofu version
          echo "::endgroup::"

          echo "::group::Check tofu version"
          status=0
          [ "$(tofu version -json | jq -r '.terraform_version')" = "${{ inputs.tofu-version }}" ] || status=$?
          echo "::endgroup::"
          exit "$status"
