---
name: Unit - tofu-fmt

on:
  workflow_call:
    inputs:
      tofu-versions:
        description: JSON array of OpenTofu versions to test.
        required: true
        type: string
      test-fixtures-dir:
        description: Directory containing the test fixtures.
        required: false
        default: test-fixtures
        type: string

permissions:
  contents: read

jobs:
  tofu-fmt:
    name: unit - tofu-fmt
    runs-on: ubuntu-slim
    strategy:
      matrix:
        tofu-version: ${{ fromJson(inputs.tofu-versions) }}
        chroot-directory:
          - fmt-passed
          - fmt-failed
        include:
          - chroot-directory: fmt-passed
            status-code: '0'
          - chroot-directory: fmt-failed
            status-code: '3'
    steps:
      - name: Checkout the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Run tofu setup
        uses: ./actions/tofu-setup
        with:
          tofu-version: ${{ matrix.tofu-version }}

      - name: Run tofu fmt
        id: tf-fmt
        uses: ./actions/tofu-fmt
        continue-on-error: true
        with:
          chroot-directory: ${{ inputs.test-fixtures-dir }}/${{ matrix.chroot-directory }}

      - name: Assert tofu fmt status code
        if: steps.tf-fmt.outputs.status-code != matrix.status-code
        run: exit 1
