---
name: Unit - tofu-import

on:
  workflow_call:
    inputs:
      tofu-versions:
        description: JSON array of OpenTofu versions to test.
        required: true
        type: string
      test-fixtures-dir:
        description: Directory containing the test fixtures.
        required: false
        default: test-fixtures
        type: string

permissions:
  contents: read

jobs:
  tofu-import:
    name: unit - tofu-import
    runs-on: ubuntu-slim
    strategy:
      matrix:
        tofu-version: ${{ fromJson(inputs.tofu-versions) }}
        chroot-directory:
          - plan-with-import
    steps:
      - name: Checkout the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Run tofu setup
        uses: ./actions/tofu-setup
        with:
          tofu-version: ${{ matrix.tofu-version }}

      - name: Run tofu plan for import test fixture
        id: tf-plan
        uses: ./actions/tofu-plan
        with:
          chroot-directory: ${{ inputs.test-fixtures-dir }}/${{ matrix.chroot-directory }}
          environment: ${{ matrix.tofu-version }}
          upload-artifact: 'false'

      - name: Assert tofu plan import count
        shell: bash
        run: |
          set -euo pipefail
          [ "${{ steps.tf-plan.outputs.plan-import-count }}" = "1" ]

      - name: Run tofu apply to import resource
        uses: ./actions/tofu-apply
        with:
          chroot-directory: ${{ inputs.test-fixtures-dir }}/${{ matrix.chroot-directory }}
          plan-file-path: ${{ steps.tf-plan.outputs.plan-file-path }}

      - name: Assert resource has been imported into state
        working-directory: ${{ inputs.test-fixtures-dir }}/${{ matrix.chroot-directory }}
        shell: bash
        run: |
          tofu state pull | jq -e '
            .resources[]
            | select(.type == "time_static" and .name == "this")
            | .instances[].attributes.rfc3339 == "2024-01-01T00:00:00Z"
          '
